author = "Arjun <arjunp0710@gmail.com>"
description = "Lapce LSP plugin for tabnine autocomplete"
display-name = "Tabine"
name = "lapce-tabnine"
version = "0.0.0"
wasm = "bin/lapce-tabnine.wasm"

[activation]
language = [""]
workspace-contains = ["**/*"]

# [config."volt.serverPath"]
# default = ""
# description = "Path to custom LSP executable"

[config."volt.serverArgs"]
default = ["--client=lapce"]
description = "client args"

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
